[ballerina.workflow]
mode = "IN_MEMORY"

[ballerina_usecases.ehr_downtime_recovery]
servicePort = 8124

slackBotToken = ""
interopOpsChannel = "#interop-ops"

gmailRefreshToken = ""
gmailClientId = ""
gmailClientSecret = ""
gmailFromAddress = "interop@example.com"
opsEmail = "ops@example.com"

emrBaseUrl = "http://localhost:9080"
