/*
 * Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package io.ballerina.lib.workflow.utils;

import io.ballerina.runtime.api.utils.StringUtils;
import io.ballerina.runtime.api.values.BString;

/**
 * The Workflow Definition Descriptor field names the runtime reads, as {@code BString} keys.
 * The descriptor is generated by the compiler plugin, which declares the same vocabulary in
 * {@code io.ballerina.lib.workflow.compiler.descriptor.DescriptorFields}; the two must agree,
 * and the descriptor-registration tests fail if they drift apart. Naming them once here keeps a
 * typo in a lookup from silently reading nothing — a missed field would leave a workflow
 * unregistered rather than raising an error.
 *
 * @since 0.9.0
 */
public final class DescriptorFields {

    /** The described workflows. */
    public static final BString WORKFLOWS = StringUtils.fromString("workflows");
    /** Name of a workflow, activity, or human task. */
    public static final BString NAME = StringUtils.fromString("name");
    /** The implementation binding: the module-level function the runtime resolves. */
    public static final BString FUNCTION = StringUtils.fromString("function");
    /** Qualified module name of a function binding. */
    public static final BString MODULE = StringUtils.fromString("module");
    /** Major version of the module a function binding names. */
    public static final BString VERSION = StringUtils.fromString("version");
    /** Activities a workflow calls. */
    public static final BString ACTIVITIES = StringUtils.fromString("activities");
    /** Human tasks a workflow awaits. */
    public static final BString HUMAN_TASKS = StringUtils.fromString("humanTasks");
    /** A human task's result slot. */
    public static final BString RESULT = StringUtils.fromString("result");
    /** The derived JSON Schema of a typed slot, when it has one. */
    public static final BString SCHEMA = StringUtils.fromString("schema");

    private DescriptorFields() {
    }
}
